### ISSUE TITLE
memory leak, maybe??

### ISSUE THREAD

**Issue by komuw** [komuw/goweb#54]
```go
var resultBenchmarkAllMiddlewares int //nolint:gochecknoglobals

func BenchmarkAllMiddlewares(b *testing.B) {
	var r int
	msg := "hello world"
	o := WithOpts("example.com")
	iterations := defaultMinSize * 2
	wrappedHandler := All(someGzipHandler(msg, iterations), o)

	b.ReportAllocs()
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		// always record the result of Fib to prevent
		// the compiler eliminating the function call.
		rec := httptest.NewRecorder()
		req := httptest.NewRequest(http.MethodGet, "/someUri", nil)
		req.Header.Add(acceptEncodingHeader, "br;q=1.0, gzip;q=0.8, *;q=0.1")
		wrappedHandler.ServeHTTP(rec, req)
		res := rec.Result()
		defer res.Body.Close()

		// fmt.Println("headers: ")
		// fmt.Println("\n\t", res.Header)
		attest.Equal(b, res.Header.Get(contentEncodingHeader), "gzip")
		attest.Equal(b, res.StatusCode, http.StatusOK)
		r = res.StatusCode
	}
	// always store the result to a package level variable
	// so the compiler cannot eliminate the Benchmark itself.
	resultBenchmarkAllMiddlewares = r
}
```
```sh
go test \
-timeout 1m \
-race \
-run=XXXX \
-bench=BenchmarkAllMiddlewares github.com/komuw/goweb/middleware \
-v \
-benchmem \
-memprofile mem.out \
-cpuprofile cpu.out
```
```bash
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xadbd00?, 0x14bf000000?})
	/usr/local/go/src/runtime/panic.go:992 +0x71
runtime.sysMap(0xc036000000, 0x7f467198bc98?, 0x7f467198bd00?)
	/usr/local/go/src/runtime/mem_linux.go:189 +0x11b
runtime.(*mheap).grow(0xe7d280, 0xa5f631?)
	/usr/local/go/src/runtime/mheap.go:1404 +0x225
runtime.(*mheap).allocSpan(0xe7d280, 0xa5f631, 0x0, 0x1)
	/usr/local/go/src/runtime/mheap.go:1170 +0x171
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:912 +0x65
runtime.systemstack()
	/usr/local/go/src/runtime/asm_amd64.s:469 +0x49

goroutine 6 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc0003ead98 sp=0xc0003ead90 pc=0x49c7a0
runtime.(*mheap).alloc(0x14bec62000?, 0xa5f631?, 0x69?)
	/usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc0003eade0 sp=0xc0003ead98 pc=0x45a685
runtime.(*mcache).allocLarge(0x4a18a5?, 0x14bec61b00, 0x1)
	/usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc0003eae30 sp=0xc0003eade0 pc=0x44aac5
runtime.mallocgc(0x14bec61b00, 0xa4b8a0, 0x1)
	/usr/local/go/src/runtime/malloc.go:1096 +0x59c fp=0xc0003eaec0 sp=0xc0003eae30 pc=0x440a9c
runtime.makeslice(0x0?, 0x8?, 0x7f4699670800?)
	/usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc0003eaee8 sp=0xc0003eaec0 pc=0x482d12
strings.(*Builder).grow(...)
	/usr/local/go/src/strings/builder.go:67
strings.(*Builder).Grow(0xc0003eaf78, 0x14bec61b00)
	/usr/local/go/src/strings/builder.go:81 +0x157 fp=0xc0003eaf48 sp=0xc0003eaee8 pc=0x5632f7
strings.Repeat({0xc0008b8000, 0x11b3dc40}, 0x12c)
	/usr/local/go/src/strings/strings.go:540 +0x87 fp=0xc0003eafa8 sp=0xc0003eaf48 pc=0x56b8a7
github.com/komuw/goweb/middleware.someGzipHandler.func1({0xbaf758?, 0xc00014c140}, 0xc0000f02c0?)
	/home/goweb/middleware/gzip_test.go:22 +0x65 fp=0xc0003eb018 sp=0xc0003eafa8 pc=0xa0b3e5
github.com/komuw/goweb/middleware.All.func1({0xbaf758, 0xc00014c140}, 0xad3cf3?)
	/home/goweb/middleware/middleware.go:113 +0x52 fp=0xc0003eb050 sp=0xc0003eb018 pc=0x9f6f52
github.com/komuw/goweb/middleware.Gzip.func1({0xbaf788, 0xc00000e1c8}, 0xc0003a8600)
	/home/goweb/middleware/gzip.go:68 +0x3ec fp=0xc0003eb158 sp=0xc0003eb050 pc=0x9f146c
github.com/komuw/goweb/middleware.Csrf.func1({0xbaf788, 0xc00000e1c8}, 0xc0003a8500)
	/home/goweb/middleware/csrf.go:148 +0x9d2 fp=0xc0003eb310 sp=0xc0003eb158 pc=0x9f06b2
github.com/komuw/goweb/middleware.Cors.func1({0xbaf788, 0xc00000e1c8}, 0xc0003a8500)
	/home/goweb/middleware/cors.go:82 +0x373 fp=0xc0003eb410 sp=0xc0003eb310 pc=0x9ecd33
github.com/komuw/goweb/middleware.Security.func1({0xbaf788, 0xc00000e1c8}, 0xc0003a8400)
	/home/goweb/middleware/security.go:112 +0xe0a fp=0xc0003eb638 sp=0xc0003eb410 pc=0x9fa44a
github.com/komuw/goweb/middleware.LoadShedder.func1({0xbaf788, 0xc00000e1c8}, 0xc000112a40?)
	/home/goweb/middleware/loadshed.go:84 +0x6e6 fp=0xc0003eb820 sp=0xc0003eb638 pc=0x9f3586
github.com/komuw/goweb/middleware.Log.func1({0xbb03b8, 0xc000112a40}, 0xc0003a8300)
	/home/goweb/middleware/log.go:98 +0xa4d fp=0xc0003ebad0 sp=0xc0003eb820 pc=0x9f57cd
github.com/komuw/goweb/middleware.Panic.func1({0xbb03b8, 0xc000112a40}, 0xc0003a8300)
	/home/goweb/middleware/panic.go:52 +0x10e fp=0xc0003ebb88 sp=0xc0003ebad0 pc=0x9f8a8e
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/go/src/net/http/server.go:2084
github.com/komuw/goweb/middleware.BenchmarkAllMiddlewares(0xc000178480)
	/home/goweb/middleware/middleware_test.go:222 +0x6a3 fp=0xc0003ebdd0 sp=0xc0003ebb88 pc=0xa19543
testing.(*B).runN(0xc000178480, 0x64)
	/usr/local/go/src/testing/benchmark.go:193 +0x1b0 fp=0xc0003ebee8 sp=0xc0003ebdd0 pc=0x582690
testing.(*B).launch(0xc000178480)
	/usr/local/go/src/testing/benchmark.go:334 +0x336 fp=0xc0003ebfc0 sp=0xc0003ebee8 pc=0x583916
testing.(*B).doBench.func1()
	/usr/local/go/src/testing/benchmark.go:284 +0x3a fp=0xc0003ebfe0 sp=0xc0003ebfc0 pc=0x58359a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0003ebfe8 sp=0xc0003ebfe0 pc=0x49e9c1
created by testing.(*B).doBench
	/usr/local/go/src/testing/benchmark.go:284 +0x9e

goroutine 1 [chan receive]:
testing.(*B).doBench(0xc000178480)
	/usr/local/go/src/testing/benchmark.go:285 +0xc5
testing.(*benchContext).processBench(0xc00013c1c8, 0xc000178480)
	/usr/local/go/src/testing/benchmark.go:589 +0x6e5
testing.(*B).run(0xc000178480)
	/usr/local/go/src/testing/benchmark.go:276 +0x96
testing.(*B).Run(0xc000178240, {0xadbfe0, 0x17}, 0xb0c840)
	/usr/local/go/src/testing/benchmark.go:677 +0x859
testing.runBenchmarks.func1(0xc000178240?)
	/usr/local/go/src/testing/benchmark.go:550 +0x9a
testing.(*B).runN(0xc000178240, 0x1)
	/usr/local/go/src/testing/benchmark.go:193 +0x1b0
testing.runBenchmarks({0xae1d66, 0x21}, 0x0?, {0xe5bf40, 0x6, 0x7f4699671328?})
	/usr/local/go/src/testing/benchmark.go:559 +0x80f
testing.(*M).Run(0xc00012ad20)
	/usr/local/go/src/testing/testing.go:1726 +0xdcd
main.main()
	_testmain.go:97 +0x2e5

goroutine 21 [sleep]:
time.Sleep(0x5f5e100)
	/usr/local/go/src/runtime/time.go:194 +0x12e
runtime/pprof.profileWriter({0xbad2e0, 0xc000126030})
	/usr/local/go/src/runtime/pprof/pprof.go:800 +0x65
created by runtime/pprof.StartCPUProfile
	/usr/local/go/src/runtime/pprof/pprof.go:785 +0x1b1
exit status 2
```

**Comment by komuw** [comment]
If we change the loop from; `for n := 0; n < b.N; n++ {` to; `for n := 0; n < 3; n++ {` 
the benchmark completes. 
`go tool pprof middleware.test cpu.out`
```bash
top -cum 30
Showing nodes accounting for 15.71s, 85.85% of 18.30s total
Dropped 34 nodes (cum <= 0.09s)
Showing top 30 nodes out of 39
      flat  flat%   sum%        cum   cum%
         0     0%     0%     14.82s 80.98%  runtime._System
    11.50s 62.84% 62.84%     11.50s 62.84%  __tsan_read
     3.11s 16.99% 79.84%      3.11s 16.99%  __tsan::MemoryAccessRange
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.All.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.BenchmarkAllMiddlewares
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.Cors.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.Csrf.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.Gzip.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.LoadShedder.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.Log.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.Panic.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.Security.func1
         0     0% 79.84%      1.99s 10.87%  github.com/komuw/goweb/middleware.someGzipHandler.func1
         0     0% 79.84%      1.99s 10.87%  testing.(*B).run1.func1
         0     0% 79.84%      1.99s 10.87%  testing.(*B).runN
         0     0% 79.84%      1.94s 10.60%  fmt.Fprint
         0     0% 79.84%      1.89s 10.33%  github.com/komuw/goweb/middleware.(*gzipRW).Write
         0     0% 79.84%      1.83s 10.00%  compress/gzip.(*Writer).Write
         0     0% 79.84%      1.83s 10.00%  github.com/komuw/goweb/middleware.(*gzipRW).handleGzipped
         0     0% 79.84%      1.81s  9.89%  compress/flate.(*compressor).encSpeed
         0     0% 79.84%      1.81s  9.89%  compress/flate.(*compressor).write
     0.03s  0.16% 80.00%      1.63s  8.91%  compress/flate.(*deflateFast).encode
     1.02s  5.57% 85.57%      1.54s  8.42%  compress/flate.(*deflateFast).matchLen
         0     0% 85.57%      0.93s  5.08%  runtime.gcBgMarkWorker
         0     0% 85.57%      0.93s  5.08%  runtime.gcBgMarkWorker.func2
         0     0% 85.57%      0.93s  5.08%  runtime.gcDrain
         0     0% 85.57%      0.93s  5.08%  runtime.markroot
         0     0% 85.57%      0.93s  5.08%  runtime.markroot.func1
     0.05s  0.27% 85.85%      0.93s  5.08%  runtime.suspendG
         0     0% 85.85%      0.93s  5.08%  runtime.systemstack
```
and if we list where the middlewares are spending time;
```sh
(pprof) list middleware.Panic
Total: 18.30s
ROUTINE ======================== github.com/komuw/goweb/middleware.Panic.func1 in /home/goweb/middleware/panic.go
         0      1.99s (flat, cum) 10.87% of Total
         .          .     47:					logger.Error(nil, flds)
         .          .     48:				}
         .          .     49:			}
         .          .     50:		}()
         .          .     51:
         .      1.99s     52:		wrappedHandler(w, r)
         .          .     53:	}
         .          .     54:}
(pprof) list middleware.Log
Total: 18.30s
ROUTINE ======================== github.com/komuw/goweb/middleware.Log.func1 in /home/goweb/middleware/log.go
         0      1.99s (flat, cum) 10.87% of Total
         .          .     93:			} else {
         .          .     94:				logger.Info(flds)
         .          .     95:			}
         .          .     96:		}()
         .          .     97:
         .      1.99s     98:		wrappedHandler(lrw, r)
         .          .     99:	}
         .          .    100:}
         .          .    101:
         .          .    102:// logRW provides an http.ResponseWriter interface, which logs requests/responses.
         .          .    103:type logRW struct {
(pprof) list middleware.LoadShedder
Total: 18.30s
ROUTINE ======================== github.com/komuw/goweb/middleware.LoadShedder.func1 in /home/goweb/middleware/loadshed.go
         0      1.99s (flat, cum) 10.87% of Total
         .          .     79:				http.StatusServiceUnavailable,
         .          .     80:			)
         .          .     81:			return
         .          .     82:		}
         .          .     83:
         .      1.99s     84:		wrappedHandler(w, r)
         .          .     85:	}
         .          .     86:}
         .          .     87:
         .          .     88:/*
         .          .     89:unsafe.Sizeof(latency{}) == 16bytes.
(pprof) list middleware.Gzip
Total: 18.30s
ROUTINE ======================== github.com/komuw/goweb/middleware.Gzip.func1 in /home/goweb/middleware/gzip.go
         0      1.99s (flat, cum) 10.87% of Total
         .          .     63:
         .          .     64:		// todo: we could detect if `w` is a `http.CloseNotifier` and do something special here.
         .          .     65:		// see: https://github.com/klauspost/compress/blob/4a97174a615ed745c450077edf0e1f7e97aabd58/gzhttp/compress.go#L383-L385
         .          .     66:		// However `http.CloseNotifier` has been deprecated sinc Go v1.11(year 2018)
         .          .     67:
         .      1.99s     68:		wrappedHandler(grw, r)
         .          .     69:	}
         .          .     70:}
         .          .     71:
         .          .     72:// gzipRW provides an http.ResponseWriter interface, which gzips
         .          .     73:// bytes before writing them to the underlying response. This doesn't close the
```
So, they are all spending time where I would expect them to; ie just calling the wrapped handler.  
So, this doesn't seem to be a cpu issue.

**Comment by komuw** [comment]
looking at the earlier stacktrace:
```bash
goroutine 6 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:436 fp=0xc0003ead98 sp=0xc0003ead90 pc=0x49c7a0
runtime.(*mheap).alloc(0x14bec62000?, 0xa5f631?, 0x69?)
	/usr/local/go/src/runtime/mheap.go:906 +0x65 fp=0xc0003eade0 sp=0xc0003ead98 pc=0x45a685
runtime.(*mcache).allocLarge(0x4a18a5?, 0x14bec61b00, 0x1)
	/usr/local/go/src/runtime/mcache.go:213 +0x85 fp=0xc0003eae30 sp=0xc0003eade0 pc=0x44aac5
runtime.mallocgc(0x14bec61b00, 0xa4b8a0, 0x1)
	/usr/local/go/src/runtime/malloc.go:1096 +0x59c fp=0xc0003eaec0 sp=0xc0003eae30 pc=0x440a9c
runtime.makeslice(0x0?, 0x8?, 0x7f4699670800?)
	/usr/local/go/src/runtime/slice.go:103 +0x52 fp=0xc0003eaee8 sp=0xc0003eaec0 pc=0x482d12
strings.(*Builder).grow(...)
	/usr/local/go/src/strings/builder.go:67
strings.(*Builder).Grow(0xc0003eaf78, 0x14bec61b00)
	/usr/local/go/src/strings/builder.go:81 +0x157 fp=0xc0003eaf48 sp=0xc0003eaee8 pc=0x5632f7
strings.Repeat({0xc0008b8000, 0x11b3dc40}, 0x12c)
	/usr/local/go/src/strings/strings.go:540 +0x87 fp=0xc0003eafa8 sp=0xc0003eaf48 pc=0x56b8a7
github.com/komuw/goweb/middleware.someGzipHandler.func1({0xbaf758?, 0xc00014c140}, 0xc0000f02c0?)
	/home/goweb/middleware/gzip_test.go:22 +0x65 fp=0xc0003eb018 sp=0xc0003eafa8 pc=0xa0b3e5
github.com/komuw/goweb/middleware.All.func1({0xbaf758, 0xc00014c140}, 0xad3cf3?)
	/home/goweb/middleware/middleware.go:113 +0x52 fp=0xc0003eb050 sp=0xc0003eb018 pc=0x9f6f52
```
If we look at what is in `middleware/gzip_test.go:22` : https://github.com/komuw/goweb/blob/07135bffe589ac97e5c6f8fc8bde63af9df98627/middleware/gzip_test.go#L22  
we can see why we would get a stack-overflow.
